safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url: http://0.0.0.0:4000

source:      .
destination: ./_site
plugins_dir: ./_plugins

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   /:title

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  input: GFM
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
